version: '3.1'

services:

  db:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: liquibase_demo
    # (this is just an example, not intended to be a production configuration)
    networks:
      - jenkins-liquibase
    ports:
      - 3306:3306
  jenkins:
    container_name: myjenkins
    image: myjenkins
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Jenkins
    networks:
      - jenkins-liquibase
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
  jenkins-liquibase:
